spring:
  application:
    name: consumer-service
  profiles:
    active: local
    
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: ap-northeast-2
      sqs:
        endpoint: http://localhost:4566
        listener:
          max-inflight-messages-per-queue: 10
          max-messages-per-poll: 10
          poll-timeout: 10s
        
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  datasource:
    url: jdbc:h2:mem:consumer-db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.demo.consumer: DEBUG
    io.awspring.cloud.sqs: DEBUG
    
app:
  sqs:
    queue-name: order-processing-queue
    dlq-name: order-processing-dlq
    sync-queue-name: sync-events-queue
    max-retry-attempts: 3
  client:
    producer-service-url: http://localhost:8080
    
---
spring:
  config:
    activate:
      on-profile: test
      
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
        
logging:
  level:
    root: WARN
    com.demo.consumer: DEBUG