spring:
  application:
    name: producer-service
  profiles:
    active: local
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: ap-northeast-2
      sqs:
        endpoint: http://localhost:4566
        
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        
  datasource:
    url: jdbc:mysql://localhost:3306/producer_db?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: producer
    password: producer123
      
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.demo.producer: DEBUG
    io.awspring.cloud.sqs: DEBUG
    
app:
  sqs:
    queue-name: order-processing-queue
    dlq-name: order-processing-dlq
    sync-queue-name: sync-events-queue
    max-retry-attempts: 3
  client:
    consumer-service-url: http://localhost:8081
    
---
spring:
  config:
    activate:
      on-profile: test
      
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
        
logging:
  level:
    root: WARN
    com.demo.producer: DEBUG